//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.servicio_local_emision {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsemision.pe.com/", ConfigurationName="servicio_local_emision.wsemision")]
    public interface wsemision {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento documento del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/generarBoletaRequest", ReplyAction="http://wsemision.pe.com/wsemision/generarBoletaResponse")]
        proyecto_vivemas.servicio_local_emision.generarBoletaResponse generarBoleta(proyecto_vivemas.servicio_local_emision.generarBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/generarBoletaRequest", ReplyAction="http://wsemision.pe.com/wsemision/generarBoletaResponse")]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarBoletaResponse> generarBoletaAsync(proyecto_vivemas.servicio_local_emision.generarBoletaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento documento del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/generarFactura2Request", ReplyAction="http://wsemision.pe.com/wsemision/generarFactura2Response")]
        proyecto_vivemas.servicio_local_emision.generarFactura2Response generarFactura2(proyecto_vivemas.servicio_local_emision.generarFactura2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/generarFactura2Request", ReplyAction="http://wsemision.pe.com/wsemision/generarFactura2Response")]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarFactura2Response> generarFactura2Async(proyecto_vivemas.servicio_local_emision.generarFactura2Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento documento del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/generarNotaCreditoRequest", ReplyAction="http://wsemision.pe.com/wsemision/generarNotaCreditoResponse")]
        proyecto_vivemas.servicio_local_emision.generarNotaCreditoResponse generarNotaCredito(proyecto_vivemas.servicio_local_emision.generarNotaCreditoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/generarNotaCreditoRequest", ReplyAction="http://wsemision.pe.com/wsemision/generarNotaCreditoResponse")]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarNotaCreditoResponse> generarNotaCreditoAsync(proyecto_vivemas.servicio_local_emision.generarNotaCreditoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento documento del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/generarNotaDebitoRequest", ReplyAction="http://wsemision.pe.com/wsemision/generarNotaDebitoResponse")]
        proyecto_vivemas.servicio_local_emision.generarNotaDebitoResponse generarNotaDebito(proyecto_vivemas.servicio_local_emision.generarNotaDebitoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/generarNotaDebitoRequest", ReplyAction="http://wsemision.pe.com/wsemision/generarNotaDebitoResponse")]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarNotaDebitoResponse> generarNotaDebitoAsync(proyecto_vivemas.servicio_local_emision.generarNotaDebitoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento documento del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/generarComunicacionBajaRequest", ReplyAction="http://wsemision.pe.com/wsemision/generarComunicacionBajaResponse")]
        proyecto_vivemas.servicio_local_emision.generarComunicacionBajaResponse generarComunicacionBaja(proyecto_vivemas.servicio_local_emision.generarComunicacionBajaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/generarComunicacionBajaRequest", ReplyAction="http://wsemision.pe.com/wsemision/generarComunicacionBajaResponse")]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarComunicacionBajaResponse> generarComunicacionBajaAsync(proyecto_vivemas.servicio_local_emision.generarComunicacionBajaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento documento del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/generarResumenBoletaRequest", ReplyAction="http://wsemision.pe.com/wsemision/generarResumenBoletaResponse")]
        proyecto_vivemas.servicio_local_emision.generarResumenBoletaResponse generarResumenBoleta(proyecto_vivemas.servicio_local_emision.generarResumenBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/generarResumenBoletaRequest", ReplyAction="http://wsemision.pe.com/wsemision/generarResumenBoletaResponse")]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarResumenBoletaResponse> generarResumenBoletaAsync(proyecto_vivemas.servicio_local_emision.generarResumenBoletaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/helloRequest", ReplyAction="http://wsemision.pe.com/wsemision/helloResponse")]
        proyecto_vivemas.servicio_local_emision.helloResponse hello(proyecto_vivemas.servicio_local_emision.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/helloRequest", ReplyAction="http://wsemision.pe.com/wsemision/helloResponse")]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.helloResponse> helloAsync(proyecto_vivemas.servicio_local_emision.helloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento documento del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/generarFacturaRequest", ReplyAction="http://wsemision.pe.com/wsemision/generarFacturaResponse")]
        proyecto_vivemas.servicio_local_emision.generarFacturaResponse generarFactura(proyecto_vivemas.servicio_local_emision.generarFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/generarFacturaRequest", ReplyAction="http://wsemision.pe.com/wsemision/generarFacturaResponse")]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarFacturaResponse> generarFacturaAsync(proyecto_vivemas.servicio_local_emision.generarFacturaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento documento del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/obtenerStatusRequest", ReplyAction="http://wsemision.pe.com/wsemision/obtenerStatusResponse")]
        proyecto_vivemas.servicio_local_emision.obtenerStatusResponse obtenerStatus(proyecto_vivemas.servicio_local_emision.obtenerStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsemision.pe.com/wsemision/obtenerStatusRequest", ReplyAction="http://wsemision.pe.com/wsemision/obtenerStatusResponse")]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.obtenerStatusResponse> obtenerStatusAsync(proyecto_vivemas.servicio_local_emision.obtenerStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarBoletaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarBoleta", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.generarBoletaRequestBody Body;
        
        public generarBoletaRequest() {
        }
        
        public generarBoletaRequest(proyecto_vivemas.servicio_local_emision.generarBoletaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarBoletaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documento;
        
        public generarBoletaRequestBody() {
        }
        
        public generarBoletaRequestBody(string documento) {
            this.documento = documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarBoletaResponse", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.generarBoletaResponseBody Body;
        
        public generarBoletaResponse() {
        }
        
        public generarBoletaResponse(proyecto_vivemas.servicio_local_emision.generarBoletaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarBoletaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public generarBoletaResponseBody() {
        }
        
        public generarBoletaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarFactura2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarFactura2", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.generarFactura2RequestBody Body;
        
        public generarFactura2Request() {
        }
        
        public generarFactura2Request(proyecto_vivemas.servicio_local_emision.generarFactura2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarFactura2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documento;
        
        public generarFactura2RequestBody() {
        }
        
        public generarFactura2RequestBody(string documento) {
            this.documento = documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarFactura2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarFactura2Response", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.generarFactura2ResponseBody Body;
        
        public generarFactura2Response() {
        }
        
        public generarFactura2Response(proyecto_vivemas.servicio_local_emision.generarFactura2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarFactura2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public generarFactura2ResponseBody() {
        }
        
        public generarFactura2ResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarNotaCreditoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarNotaCredito", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.generarNotaCreditoRequestBody Body;
        
        public generarNotaCreditoRequest() {
        }
        
        public generarNotaCreditoRequest(proyecto_vivemas.servicio_local_emision.generarNotaCreditoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarNotaCreditoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documento;
        
        public generarNotaCreditoRequestBody() {
        }
        
        public generarNotaCreditoRequestBody(string documento) {
            this.documento = documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarNotaCreditoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarNotaCreditoResponse", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.generarNotaCreditoResponseBody Body;
        
        public generarNotaCreditoResponse() {
        }
        
        public generarNotaCreditoResponse(proyecto_vivemas.servicio_local_emision.generarNotaCreditoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarNotaCreditoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public generarNotaCreditoResponseBody() {
        }
        
        public generarNotaCreditoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarNotaDebitoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarNotaDebito", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.generarNotaDebitoRequestBody Body;
        
        public generarNotaDebitoRequest() {
        }
        
        public generarNotaDebitoRequest(proyecto_vivemas.servicio_local_emision.generarNotaDebitoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarNotaDebitoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documento;
        
        public generarNotaDebitoRequestBody() {
        }
        
        public generarNotaDebitoRequestBody(string documento) {
            this.documento = documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarNotaDebitoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarNotaDebitoResponse", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.generarNotaDebitoResponseBody Body;
        
        public generarNotaDebitoResponse() {
        }
        
        public generarNotaDebitoResponse(proyecto_vivemas.servicio_local_emision.generarNotaDebitoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarNotaDebitoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public generarNotaDebitoResponseBody() {
        }
        
        public generarNotaDebitoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarComunicacionBajaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarComunicacionBaja", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.generarComunicacionBajaRequestBody Body;
        
        public generarComunicacionBajaRequest() {
        }
        
        public generarComunicacionBajaRequest(proyecto_vivemas.servicio_local_emision.generarComunicacionBajaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarComunicacionBajaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documento;
        
        public generarComunicacionBajaRequestBody() {
        }
        
        public generarComunicacionBajaRequestBody(string documento) {
            this.documento = documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarComunicacionBajaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarComunicacionBajaResponse", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.generarComunicacionBajaResponseBody Body;
        
        public generarComunicacionBajaResponse() {
        }
        
        public generarComunicacionBajaResponse(proyecto_vivemas.servicio_local_emision.generarComunicacionBajaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarComunicacionBajaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public generarComunicacionBajaResponseBody() {
        }
        
        public generarComunicacionBajaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarResumenBoletaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarResumenBoleta", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.generarResumenBoletaRequestBody Body;
        
        public generarResumenBoletaRequest() {
        }
        
        public generarResumenBoletaRequest(proyecto_vivemas.servicio_local_emision.generarResumenBoletaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarResumenBoletaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documento;
        
        public generarResumenBoletaRequestBody() {
        }
        
        public generarResumenBoletaRequestBody(string documento) {
            this.documento = documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarResumenBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarResumenBoletaResponse", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.generarResumenBoletaResponseBody Body;
        
        public generarResumenBoletaResponse() {
        }
        
        public generarResumenBoletaResponse(proyecto_vivemas.servicio_local_emision.generarResumenBoletaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarResumenBoletaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public generarResumenBoletaResponseBody() {
        }
        
        public generarResumenBoletaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(proyecto_vivemas.servicio_local_emision.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(proyecto_vivemas.servicio_local_emision.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarFactura", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.generarFacturaRequestBody Body;
        
        public generarFacturaRequest() {
        }
        
        public generarFacturaRequest(proyecto_vivemas.servicio_local_emision.generarFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarFacturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documento;
        
        public generarFacturaRequestBody() {
        }
        
        public generarFacturaRequestBody(string documento) {
            this.documento = documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarFacturaResponse", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.generarFacturaResponseBody Body;
        
        public generarFacturaResponse() {
        }
        
        public generarFacturaResponse(proyecto_vivemas.servicio_local_emision.generarFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarFacturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public generarFacturaResponseBody() {
        }
        
        public generarFacturaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerStatus", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.obtenerStatusRequestBody Body;
        
        public obtenerStatusRequest() {
        }
        
        public obtenerStatusRequest(proyecto_vivemas.servicio_local_emision.obtenerStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class obtenerStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documento;
        
        public obtenerStatusRequestBody() {
        }
        
        public obtenerStatusRequestBody(string documento) {
            this.documento = documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerStatusResponse", Namespace="http://wsemision.pe.com/", Order=0)]
        public proyecto_vivemas.servicio_local_emision.obtenerStatusResponseBody Body;
        
        public obtenerStatusResponse() {
        }
        
        public obtenerStatusResponse(proyecto_vivemas.servicio_local_emision.obtenerStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class obtenerStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public obtenerStatusResponseBody() {
        }
        
        public obtenerStatusResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsemisionChannel : proyecto_vivemas.servicio_local_emision.wsemision, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsemisionClient : System.ServiceModel.ClientBase<proyecto_vivemas.servicio_local_emision.wsemision>, proyecto_vivemas.servicio_local_emision.wsemision {
        
        public wsemisionClient() {
        }
        
        public wsemisionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsemisionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsemisionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsemisionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyecto_vivemas.servicio_local_emision.generarBoletaResponse proyecto_vivemas.servicio_local_emision.wsemision.generarBoleta(proyecto_vivemas.servicio_local_emision.generarBoletaRequest request) {
            return base.Channel.generarBoleta(request);
        }
        
        public string generarBoleta(string documento) {
            proyecto_vivemas.servicio_local_emision.generarBoletaRequest inValue = new proyecto_vivemas.servicio_local_emision.generarBoletaRequest();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.generarBoletaRequestBody();
            inValue.Body.documento = documento;
            proyecto_vivemas.servicio_local_emision.generarBoletaResponse retVal = ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).generarBoleta(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarBoletaResponse> proyecto_vivemas.servicio_local_emision.wsemision.generarBoletaAsync(proyecto_vivemas.servicio_local_emision.generarBoletaRequest request) {
            return base.Channel.generarBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarBoletaResponse> generarBoletaAsync(string documento) {
            proyecto_vivemas.servicio_local_emision.generarBoletaRequest inValue = new proyecto_vivemas.servicio_local_emision.generarBoletaRequest();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.generarBoletaRequestBody();
            inValue.Body.documento = documento;
            return ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).generarBoletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyecto_vivemas.servicio_local_emision.generarFactura2Response proyecto_vivemas.servicio_local_emision.wsemision.generarFactura2(proyecto_vivemas.servicio_local_emision.generarFactura2Request request) {
            return base.Channel.generarFactura2(request);
        }
        
        public string generarFactura2(string documento) {
            proyecto_vivemas.servicio_local_emision.generarFactura2Request inValue = new proyecto_vivemas.servicio_local_emision.generarFactura2Request();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.generarFactura2RequestBody();
            inValue.Body.documento = documento;
            proyecto_vivemas.servicio_local_emision.generarFactura2Response retVal = ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).generarFactura2(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarFactura2Response> proyecto_vivemas.servicio_local_emision.wsemision.generarFactura2Async(proyecto_vivemas.servicio_local_emision.generarFactura2Request request) {
            return base.Channel.generarFactura2Async(request);
        }
        
        public System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarFactura2Response> generarFactura2Async(string documento) {
            proyecto_vivemas.servicio_local_emision.generarFactura2Request inValue = new proyecto_vivemas.servicio_local_emision.generarFactura2Request();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.generarFactura2RequestBody();
            inValue.Body.documento = documento;
            return ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).generarFactura2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyecto_vivemas.servicio_local_emision.generarNotaCreditoResponse proyecto_vivemas.servicio_local_emision.wsemision.generarNotaCredito(proyecto_vivemas.servicio_local_emision.generarNotaCreditoRequest request) {
            return base.Channel.generarNotaCredito(request);
        }
        
        public string generarNotaCredito(string documento) {
            proyecto_vivemas.servicio_local_emision.generarNotaCreditoRequest inValue = new proyecto_vivemas.servicio_local_emision.generarNotaCreditoRequest();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.generarNotaCreditoRequestBody();
            inValue.Body.documento = documento;
            proyecto_vivemas.servicio_local_emision.generarNotaCreditoResponse retVal = ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).generarNotaCredito(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarNotaCreditoResponse> proyecto_vivemas.servicio_local_emision.wsemision.generarNotaCreditoAsync(proyecto_vivemas.servicio_local_emision.generarNotaCreditoRequest request) {
            return base.Channel.generarNotaCreditoAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarNotaCreditoResponse> generarNotaCreditoAsync(string documento) {
            proyecto_vivemas.servicio_local_emision.generarNotaCreditoRequest inValue = new proyecto_vivemas.servicio_local_emision.generarNotaCreditoRequest();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.generarNotaCreditoRequestBody();
            inValue.Body.documento = documento;
            return ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).generarNotaCreditoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyecto_vivemas.servicio_local_emision.generarNotaDebitoResponse proyecto_vivemas.servicio_local_emision.wsemision.generarNotaDebito(proyecto_vivemas.servicio_local_emision.generarNotaDebitoRequest request) {
            return base.Channel.generarNotaDebito(request);
        }
        
        public string generarNotaDebito(string documento) {
            proyecto_vivemas.servicio_local_emision.generarNotaDebitoRequest inValue = new proyecto_vivemas.servicio_local_emision.generarNotaDebitoRequest();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.generarNotaDebitoRequestBody();
            inValue.Body.documento = documento;
            proyecto_vivemas.servicio_local_emision.generarNotaDebitoResponse retVal = ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).generarNotaDebito(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarNotaDebitoResponse> proyecto_vivemas.servicio_local_emision.wsemision.generarNotaDebitoAsync(proyecto_vivemas.servicio_local_emision.generarNotaDebitoRequest request) {
            return base.Channel.generarNotaDebitoAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarNotaDebitoResponse> generarNotaDebitoAsync(string documento) {
            proyecto_vivemas.servicio_local_emision.generarNotaDebitoRequest inValue = new proyecto_vivemas.servicio_local_emision.generarNotaDebitoRequest();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.generarNotaDebitoRequestBody();
            inValue.Body.documento = documento;
            return ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).generarNotaDebitoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyecto_vivemas.servicio_local_emision.generarComunicacionBajaResponse proyecto_vivemas.servicio_local_emision.wsemision.generarComunicacionBaja(proyecto_vivemas.servicio_local_emision.generarComunicacionBajaRequest request) {
            return base.Channel.generarComunicacionBaja(request);
        }
        
        public string generarComunicacionBaja(string documento) {
            proyecto_vivemas.servicio_local_emision.generarComunicacionBajaRequest inValue = new proyecto_vivemas.servicio_local_emision.generarComunicacionBajaRequest();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.generarComunicacionBajaRequestBody();
            inValue.Body.documento = documento;
            proyecto_vivemas.servicio_local_emision.generarComunicacionBajaResponse retVal = ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).generarComunicacionBaja(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarComunicacionBajaResponse> proyecto_vivemas.servicio_local_emision.wsemision.generarComunicacionBajaAsync(proyecto_vivemas.servicio_local_emision.generarComunicacionBajaRequest request) {
            return base.Channel.generarComunicacionBajaAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarComunicacionBajaResponse> generarComunicacionBajaAsync(string documento) {
            proyecto_vivemas.servicio_local_emision.generarComunicacionBajaRequest inValue = new proyecto_vivemas.servicio_local_emision.generarComunicacionBajaRequest();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.generarComunicacionBajaRequestBody();
            inValue.Body.documento = documento;
            return ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).generarComunicacionBajaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyecto_vivemas.servicio_local_emision.generarResumenBoletaResponse proyecto_vivemas.servicio_local_emision.wsemision.generarResumenBoleta(proyecto_vivemas.servicio_local_emision.generarResumenBoletaRequest request) {
            return base.Channel.generarResumenBoleta(request);
        }
        
        public string generarResumenBoleta(string documento) {
            proyecto_vivemas.servicio_local_emision.generarResumenBoletaRequest inValue = new proyecto_vivemas.servicio_local_emision.generarResumenBoletaRequest();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.generarResumenBoletaRequestBody();
            inValue.Body.documento = documento;
            proyecto_vivemas.servicio_local_emision.generarResumenBoletaResponse retVal = ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).generarResumenBoleta(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarResumenBoletaResponse> proyecto_vivemas.servicio_local_emision.wsemision.generarResumenBoletaAsync(proyecto_vivemas.servicio_local_emision.generarResumenBoletaRequest request) {
            return base.Channel.generarResumenBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarResumenBoletaResponse> generarResumenBoletaAsync(string documento) {
            proyecto_vivemas.servicio_local_emision.generarResumenBoletaRequest inValue = new proyecto_vivemas.servicio_local_emision.generarResumenBoletaRequest();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.generarResumenBoletaRequestBody();
            inValue.Body.documento = documento;
            return ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).generarResumenBoletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyecto_vivemas.servicio_local_emision.helloResponse proyecto_vivemas.servicio_local_emision.wsemision.hello(proyecto_vivemas.servicio_local_emision.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            proyecto_vivemas.servicio_local_emision.helloRequest inValue = new proyecto_vivemas.servicio_local_emision.helloRequest();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.helloRequestBody();
            inValue.Body.name = name;
            proyecto_vivemas.servicio_local_emision.helloResponse retVal = ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.helloResponse> proyecto_vivemas.servicio_local_emision.wsemision.helloAsync(proyecto_vivemas.servicio_local_emision.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.helloResponse> helloAsync(string name) {
            proyecto_vivemas.servicio_local_emision.helloRequest inValue = new proyecto_vivemas.servicio_local_emision.helloRequest();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.helloRequestBody();
            inValue.Body.name = name;
            return ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyecto_vivemas.servicio_local_emision.generarFacturaResponse proyecto_vivemas.servicio_local_emision.wsemision.generarFactura(proyecto_vivemas.servicio_local_emision.generarFacturaRequest request) {
            return base.Channel.generarFactura(request);
        }
        
        public string generarFactura(string documento) {
            proyecto_vivemas.servicio_local_emision.generarFacturaRequest inValue = new proyecto_vivemas.servicio_local_emision.generarFacturaRequest();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.generarFacturaRequestBody();
            inValue.Body.documento = documento;
            proyecto_vivemas.servicio_local_emision.generarFacturaResponse retVal = ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).generarFactura(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarFacturaResponse> proyecto_vivemas.servicio_local_emision.wsemision.generarFacturaAsync(proyecto_vivemas.servicio_local_emision.generarFacturaRequest request) {
            return base.Channel.generarFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.generarFacturaResponse> generarFacturaAsync(string documento) {
            proyecto_vivemas.servicio_local_emision.generarFacturaRequest inValue = new proyecto_vivemas.servicio_local_emision.generarFacturaRequest();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.generarFacturaRequestBody();
            inValue.Body.documento = documento;
            return ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).generarFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyecto_vivemas.servicio_local_emision.obtenerStatusResponse proyecto_vivemas.servicio_local_emision.wsemision.obtenerStatus(proyecto_vivemas.servicio_local_emision.obtenerStatusRequest request) {
            return base.Channel.obtenerStatus(request);
        }
        
        public string obtenerStatus(string documento) {
            proyecto_vivemas.servicio_local_emision.obtenerStatusRequest inValue = new proyecto_vivemas.servicio_local_emision.obtenerStatusRequest();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.obtenerStatusRequestBody();
            inValue.Body.documento = documento;
            proyecto_vivemas.servicio_local_emision.obtenerStatusResponse retVal = ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).obtenerStatus(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.obtenerStatusResponse> proyecto_vivemas.servicio_local_emision.wsemision.obtenerStatusAsync(proyecto_vivemas.servicio_local_emision.obtenerStatusRequest request) {
            return base.Channel.obtenerStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyecto_vivemas.servicio_local_emision.obtenerStatusResponse> obtenerStatusAsync(string documento) {
            proyecto_vivemas.servicio_local_emision.obtenerStatusRequest inValue = new proyecto_vivemas.servicio_local_emision.obtenerStatusRequest();
            inValue.Body = new proyecto_vivemas.servicio_local_emision.obtenerStatusRequestBody();
            inValue.Body.documento = documento;
            return ((proyecto_vivemas.servicio_local_emision.wsemision)(this)).obtenerStatusAsync(inValue);
        }
    }
}
