//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class anexoscontratoproforma
    {
        public long anexocontratoproforma_id { get; set; }
        public Nullable<long> anexocontratoproforma_contrato_id { get; set; }
        public Nullable<long> anexocontratoproforma_proformauif_id { get; set; }
        public Nullable<long> anexocontratoproforma_tipopropietario_id { get; set; }
    
        public virtual tipospropietario tipospropietario { get; set; }
        public virtual proformasuif proformasuif { get; set; }
        public virtual contratos contratos { get; set; }
    }
}
