//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class anexoscontratocotizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public anexoscontratocotizacion()
        {
            this.cuotas = new HashSet<cuotas>();
        }
    
        public long anexocontratocotizacion_id { get; set; }
        public Nullable<long> anexocontratocotizacion_contrato_id { get; set; }
        public Nullable<long> anexocontratocotizacion_cotizacion_id { get; set; }
        public Nullable<System.DateTime> anexocontratocotizacion_fechapagoefectivo { get; set; }
        public Nullable<decimal> anexocontratocotizacion_montoefectivo { get; set; }
        public Nullable<decimal> anexocontratocotizacion_montoefectivofinanciado { get; set; }
        public Nullable<int> anexocontratocotizacion_montoefectivo_cuotas { get; set; }
        public Nullable<decimal> anexocontratocotizacion_montocuotasefectivo { get; set; }
        public Nullable<System.DateTime> anexocontratocotizacion_fechacreacion { get; set; }
        public Nullable<long> anexocontratocotizacion_usuariocreacion { get; set; }
        public Nullable<System.DateTime> anexocontratocotizacion_fechamodificacion { get; set; }
        public Nullable<long> anexocontratocotizacion_usuariomodificacion { get; set; }
    
        public virtual cotizaciones cotizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuotas> cuotas { get; set; }
        public virtual contratos contratos { get; set; }
    }
}
