//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class canalescontacto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public canalescontacto()
        {
            this.clientes = new HashSet<clientes>();
        }
    
        public long canalcontacto_id { get; set; }
        public Nullable<long> canalcontacto_mediocontacto_id { get; set; }
        public Nullable<long> canalcontacto_idanterior { get; set; }
        public string canalcontacto_descripcion { get; set; }
        public Nullable<bool> canalcontacto_estado { get; set; }
    
        public virtual medioscontacto medioscontacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clientes> clientes { get; set; }
    }
}
