//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clientes()
        {
            this.interesesclienteproyecto = new HashSet<interesesclienteproyecto>();
            this.separaciones = new HashSet<separaciones>();
            this.cotizaciones = new HashSet<cotizaciones>();
            this.proformasuif = new HashSet<proformasuif>();
        }
    
        public long cliente_id { get; set; }
        public Nullable<long> cliente_empresa_id { get; set; }
        public Nullable<long> cliente_tipopersona_id { get; set; }
        public Nullable<long> cliente_tipodocumentoidentidad_id { get; set; }
        public Nullable<long> cliente_estadocivil_id { get; set; }
        public Nullable<long> cliente_promotor_id { get; set; }
        public Nullable<long> cliente_departamento_id { get; set; }
        public Nullable<long> cliente_provincia_id { get; set; }
        public Nullable<long> cliente_distrito_id { get; set; }
        public Nullable<long> cliente_canalcontacto_id { get; set; }
        public Nullable<long> cliente_estadoproceso_id { get; set; }
        public Nullable<long> cliente_estadocaptacioncliente_id { get; set; }
        public Nullable<long> cliente_estadointerescliente_id { get; set; }
        public Nullable<long> cliente_codigoanterior { get; set; }
        public string cliente_nrodocumento { get; set; }
        public string cliente_razonsocial { get; set; }
        public string cliente_nombrecomercial { get; set; }
        public string cliente_direccion { get; set; }
        public string cliente_nrocontacto { get; set; }
        public string cliente_nrocontactoauxiliar { get; set; }
        public string cliente_email { get; set; }
        public Nullable<long> cliente_usuariocreacion { get; set; }
        public Nullable<System.DateTime> cliente_fechacreacion { get; set; }
        public Nullable<long> cliente_usuariomodificacion { get; set; }
        public Nullable<System.DateTime> cliente_fechamodificacion { get; set; }
        public Nullable<bool> cliente_escasuarinas { get; set; }
    
        public virtual canalescontacto canalescontacto { get; set; }
        public virtual distritos distritos { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual estadoscaptacioncliente estadoscaptacioncliente { get; set; }
        public virtual estadoscivil estadoscivil { get; set; }
        public virtual estadosinterescliente estadosinterescliente { get; set; }
        public virtual estadosproceso estadosproceso { get; set; }
        public virtual tiposdocumentoidentidad tiposdocumentoidentidad { get; set; }
        public virtual tipospersona tipospersona { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<interesesclienteproyecto> interesesclienteproyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<separaciones> separaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizaciones> cotizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proformasuif> proformasuif { get; set; }
    }
}
