//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuraciones
    {
        public long configuracion_id { get; set; }
        public Nullable<decimal> configuracion_tipocambiointerno { get; set; }
        public Nullable<long> configuracion_empresa_id { get; set; }
        public string configuracion_rutafactura { get; set; }
        public string configuracion_rutaboleta { get; set; }
        public string configuracion_rutanotacredito { get; set; }
        public string configuracion_rutacdrfactura { get; set; }
        public string configuracion_rutacdrboleta { get; set; }
        public string configuracion_rutacdrnotacredito { get; set; }
        public string configuracion_rutafirmadigital { get; set; }
        public string configuracion_passfirmadigital { get; set; }
        public string configuracion_credencialfirmadigital { get; set; }
        public string configuracion_passcredencialfirmadigital { get; set; }
        public string configuracion_usuarioemisor { get; set; }
        public string configuracion_passemisor { get; set; }
    
        public virtual empresas empresas { get; set; }
    }
}
