//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coordenadaslotes
    {
        public long coordenadaslote_id { get; set; }
        public Nullable<long> coordenadaslote_lote_id { get; set; }
        public string coordenadaslote_coordenada { get; set; }
    
        public virtual lotes lotes { get; set; }
    }
}
