//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cotizaciones()
        {
            this.anexoscontratocotizacion = new HashSet<anexoscontratocotizacion>();
        }
    
        public long cotizacion_id { get; set; }
        public Nullable<long> cotizacion_proyecto_id { get; set; }
        public Nullable<long> cotizacion_tipocambio_id { get; set; }
        public Nullable<long> cotizacion_cliente_id { get; set; }
        public Nullable<long> cotizacion_lote_id { get; set; }
        public Nullable<long> cotizacion_promotor_id { get; set; }
        public Nullable<long> cotizacion_moneda_id { get; set; }
        public string cotizacion_proyecto_nombre { get; set; }
        public string cotizacion_promotor_nombre { get; set; }
        public Nullable<decimal> cotizacion_tipocambio_precioventa { get; set; }
        public Nullable<System.DateTime> cotizacion_tipocambio_fecha { get; set; }
        public string cotizacion_cliente_razonsocial { get; set; }
        public string cotizacion_cliente_referenciadomicilio { get; set; }
        public string cotizacion_lote_nombre { get; set; }
        public Nullable<decimal> cotizacion_lote_areatotal { get; set; }
        public Nullable<decimal> cotizacion_lote_preciometro { get; set; }
        public Nullable<decimal> cotizacion_preciototal { get; set; }
        public Nullable<decimal> cotizacion_porcentajeinicial { get; set; }
        public Nullable<decimal> cotizacion_montoinicial { get; set; }
        public Nullable<decimal> cotizacion_porcentajefinanciado { get; set; }
        public Nullable<decimal> cotizacion_montofinanciado { get; set; }
        public Nullable<int> cotizacion_cantidadcuotas { get; set; }
        public Nullable<decimal> cotizacion_montocuotas { get; set; }
        public Nullable<System.DateTime> cotizacion_fechainiciopagos { get; set; }
        public Nullable<long> cotizacion_idanterior { get; set; }
        public Nullable<System.DateTime> cotizacion_fechacreacion { get; set; }
        public Nullable<long> cotizacion_usuariocreacion { get; set; }
        public Nullable<System.DateTime> cotizacion_fechamodificacion { get; set; }
        public Nullable<long> cotizacion_usuariomodificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<anexoscontratocotizacion> anexoscontratocotizacion { get; set; }
        public virtual clientes clientes { get; set; }
        public virtual lotes lotes { get; set; }
        public virtual monedas monedas { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual proyectos proyectos { get; set; }
        public virtual tiposcambio tiposcambio { get; set; }
    }
}
