//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuotas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuotas()
        {
            this.pagos = new HashSet<pagos>();
        }
    
        public long cuota_id { get; set; }
        public Nullable<long> cuota_anexocontratocotizacion_id { get; set; }
        public Nullable<long> cuota_idanterior { get; set; }
        public string cuota_numeracion { get; set; }
        public Nullable<System.DateTime> cuota_fechavencimiento { get; set; }
        public Nullable<decimal> cuota_monto { get; set; }
        public Nullable<decimal> cuota_montopagado { get; set; }
        public Nullable<bool> cuota_estado { get; set; }
        public Nullable<System.DateTime> cuota_fechacreacion { get; set; }
        public Nullable<long> cuota_usuariocreacion { get; set; }
        public Nullable<System.DateTime> cuota_fechamodificacion { get; set; }
        public Nullable<long> cuota_usuariomodificacion { get; set; }
    
        public virtual anexoscontratocotizacion anexoscontratocotizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagos> pagos { get; set; }
    }
}
