//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datosencuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public datosencuesta()
        {
            this.encuestas = new HashSet<encuestas>();
        }
    
        public long datoencuesta_id { get; set; }
        public Nullable<long> datoencuesta_tipoencuesta_id { get; set; }
        public string datoencuesta_cliente_nombre { get; set; }
        public Nullable<System.DateTime> datoencuesta_fecha { get; set; }
        public string datoencuesta_observaciones { get; set; }
    
        public virtual tiposencuesta tiposencuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<encuestas> encuestas { get; set; }
    }
}
