//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentosventadetalle
    {
        public long documentoventadetalle_id { get; set; }
        public Nullable<long> documentoventadetalle_documentoventa_id { get; set; }
        public string documentoventadetalle_descripcion { get; set; }
        public string documentoventadetalle_unidadmedida_codigo { get; set; }
        public Nullable<decimal> documentoventadetalle_cantidad { get; set; }
        public string documentoventadetalle_codigo { get; set; }
        public string documentoventadetalle_tipoventasunat { get; set; }
        public string documentoventadetalle_tipoafectacion { get; set; }
        public Nullable<decimal> documentoventadetalle_subtotal { get; set; }
        public Nullable<decimal> documentoventadetalle_igv { get; set; }
        public Nullable<decimal> documentoventadetalle_total { get; set; }
        public Nullable<System.DateTime> documentoventadetalle_fechacreacion { get; set; }
        public Nullable<long> documentoventadetalle_usuariocreacion { get; set; }
        public Nullable<System.DateTime> documentoventadetalle_fechamodificacion { get; set; }
        public Nullable<long> documentoventadetalle_usuariomodificacion { get; set; }
    
        public virtual documentosventa documentosventa { get; set; }
    }
}
