//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentosventa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public documentosventa()
        {
            this.documentosventadetalle = new HashSet<documentosventadetalle>();
            this.notascredito = new HashSet<notascredito>();
        }
    
        public long documentoventa_id { get; set; }
        public Nullable<long> documentoventa_empresa_id { get; set; }
        public Nullable<long> documentoventa_tipodocumentoventa_id { get; set; }
        public Nullable<long> documentoventa_estadodocumento_id { get; set; }
        public Nullable<long> documentoventa_transaccion_id { get; set; }
        public Nullable<long> documentoventa_tipometodopago_id { get; set; }
        public Nullable<long> documentoventa_moneda_id { get; set; }
        public string documentoventa_tipoemision { get; set; }
        public string documentoventa_fechaemision { get; set; }
        public string documentoventa_horaemision { get; set; }
        public string documentoventa_fechavencimiento { get; set; }
        public string documentoventa_empresa_razonsocial { get; set; }
        public string documentoventa_empresa_nrodocumento { get; set; }
        public string documentoventa_empresa_tipodocumentoidentidad_codigo { get; set; }
        public string documentoventa_empresa_ubigeo { get; set; }
        public string documentoventa_empresa_direccion { get; set; }
        public string documentoventa_empresa_zona { get; set; }
        public string documentoventa_empresa_distrito { get; set; }
        public string documentoventa_empresa_provincia { get; set; }
        public string documentoventa_empresa_departamento { get; set; }
        public string documentoventa_empresa_codigopais { get; set; }
        public string documentoventa_tipodocumentoventa_codigo { get; set; }
        public string documentoventa_serie_serie { get; set; }
        public string documentoventa_serie_numeracion { get; set; }
        public string documentoventa_cliente_nombre { get; set; }
        public string documentoventa_cliente_nrodocumento { get; set; }
        public string documentoventa_cliente_tipodocumentoidentidad_codigo { get; set; }
        public string documentoventa_moneda_codigo { get; set; }
        public Nullable<decimal> documentoventa_subtotal { get; set; }
        public Nullable<decimal> documentoventa_igv { get; set; }
        public Nullable<decimal> documentoventa_total { get; set; }
        public string documentoventa_condicioncodigo { get; set; }
        public string documentoventa_totalletras { get; set; }
        public Nullable<System.DateTime> documentoventa_fechacreacion { get; set; }
        public Nullable<long> documentoventa_usuariocreacion { get; set; }
        public Nullable<System.DateTime> documentoventa_fechamodificacion { get; set; }
        public Nullable<long> documentoventa_usuariomodificacion { get; set; }
        public string documentoventa_estadosunat { get; set; }
        public string documentoventa_digestvalue { get; set; }
        public string documentoventa_banco_nombre { get; set; }
        public string documentoventa_cuenta_cuenta { get; set; }
        public Nullable<System.DateTime> documentoventa_fechadeposito { get; set; }
        public string documentoventa_nrooperacion { get; set; }
    
        public virtual empresas empresas { get; set; }
        public virtual estadosdocumento estadosdocumento { get; set; }
        public virtual monedas monedas { get; set; }
        public virtual tiposdocumentoventa tiposdocumentoventa { get; set; }
        public virtual tiposmetodopago tiposmetodopago { get; set; }
        public virtual transacciones transacciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentosventadetalle> documentosventadetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notascredito> notascredito { get; set; }
    }
}
