//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class encuestas
    {
        public long encuesta_id { get; set; }
        public Nullable<long> encuesta_datoencuesta_id { get; set; }
        public Nullable<long> encuesta_pregunta_id { get; set; }
        public Nullable<long> encuesta_respuesta_id { get; set; }
    
        public virtual datosencuesta datosencuesta { get; set; }
        public virtual preguntas preguntas { get; set; }
        public virtual respuestas respuestas { get; set; }
    }
}
