//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interesesclienteproyecto
    {
        public long interesclienteproyecto_id { get; set; }
        public Nullable<long> interesclienteproyecto_cliente_id { get; set; }
        public Nullable<long> interesclienteproyecto_proyecto_id { get; set; }
    
        public virtual proyectos proyectos { get; set; }
        public virtual clientes clientes { get; set; }
    }
}
