//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lotes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lotes()
        {
            this.coordenadaslotes = new HashSet<coordenadaslotes>();
            this.separaciones = new HashSet<separaciones>();
            this.cotizaciones = new HashSet<cotizaciones>();
            this.proformasuif = new HashSet<proformasuif>();
        }
    
        public long lote_id { get; set; }
        public Nullable<long> lote_proyecto_id { get; set; }
        public string lote_forma { get; set; }
        public string lote_manzana { get; set; }
        public string lote_numero { get; set; }
        public string lote_nombre { get; set; }
        public Nullable<long> lote_usuariocreacion { get; set; }
        public Nullable<System.DateTime> lote_fechacreacion { get; set; }
        public Nullable<long> lote_usuariomodificacion { get; set; }
        public Nullable<System.DateTime> lote_fechamodificacion { get; set; }
        public Nullable<long> lote_estadolote_id { get; set; }
        public Nullable<decimal> lote_areatotal { get; set; }
        public Nullable<decimal> lote_perimetro { get; set; }
        public Nullable<decimal> lote_preciometro { get; set; }
        public Nullable<decimal> lote_precio { get; set; }
        public Nullable<decimal> lote_linderofrente { get; set; }
        public Nullable<decimal> lote_linderoderecha { get; set; }
        public Nullable<decimal> lote_linderoizquierda { get; set; }
        public Nullable<decimal> lote_linderoatras { get; set; }
        public Nullable<bool> lote_comercial { get; set; }
        public Nullable<long> lote_idanterior { get; set; }
    
        public virtual proyectos proyectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coordenadaslotes> coordenadaslotes { get; set; }
        public virtual estadoslote estadoslote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<separaciones> separaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizaciones> cotizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proformasuif> proformasuif { get; set; }
    }
}
