//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notascredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public notascredito()
        {
            this.notascreditodetalle = new HashSet<notascreditodetalle>();
        }
    
        public long notacredito_id { get; set; }
        public Nullable<long> notacredito_empresa_id { get; set; }
        public Nullable<long> notacredito_tipodocumentoventa_id { get; set; }
        public Nullable<long> notacredito_estadodocumento_id { get; set; }
        public Nullable<long> notacredito_documentoventa_id { get; set; }
        public Nullable<long> notacredito_moneda_id { get; set; }
        public Nullable<long> notacredito_tiponotacredito_id { get; set; }
        public string notacredito_tipoemision { get; set; }
        public string notacredito_fechaemision { get; set; }
        public string notacredito_horaemision { get; set; }
        public string notacredito_empresa_razonsocial { get; set; }
        public string notacredito_empresa_nrodocumento { get; set; }
        public string notacredito_empresa_tipodocumentoideintidad_codigo { get; set; }
        public string notacredito_empresa_ubigeo { get; set; }
        public string notacredito_empresa_direccion { get; set; }
        public string notacredito_empresa_zona { get; set; }
        public string notacredito_empresa_distrito { get; set; }
        public string notacredito_empresa_provincia { get; set; }
        public string notacredito_empresa_departamento { get; set; }
        public string notacredito_empresa_codigopais { get; set; }
        public string notacredito_tipodocumentoventa_codigo { get; set; }
        public string notacredito_serie_serie { get; set; }
        public string notacredito_serie_numeracion { get; set; }
        public string notacredito_cliente_nombre { get; set; }
        public string notacredito_cliente_nrodocumento { get; set; }
        public string notacredito_cliente_tipodocumentoidentidad_codigo { get; set; }
        public string notacredito_moneda_codigo { get; set; }
        public Nullable<decimal> notacredito_subtotal { get; set; }
        public Nullable<decimal> notacredito_igv { get; set; }
        public Nullable<decimal> notacredito_total { get; set; }
        public string notacredito_seriereferencia { get; set; }
        public string notacredito_numeracionreferencia { get; set; }
        public string notacredito_tipodocumentoventa_codigoreferencia { get; set; }
        public string notacredito_tiponotacredito_codigo { get; set; }
        public string notacredito_descripcionnota { get; set; }
        public string notacredito_totalletras { get; set; }
        public string notacredito_estadosunat { get; set; }
        public string notacredito_digestvalue { get; set; }
        public Nullable<long> notacredito_usuariocreacion { get; set; }
        public Nullable<System.DateTime> notacredito_fechacreacion { get; set; }
        public Nullable<long> notacredito_usuariomodificacion { get; set; }
        public Nullable<System.DateTime> notacredito_fechamodificacion { get; set; }
    
        public virtual documentosventa documentosventa { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual estadosdocumento estadosdocumento { get; set; }
        public virtual monedas monedas { get; set; }
        public virtual tiposdocumentoventa tiposdocumentoventa { get; set; }
        public virtual tiposnotacredito tiposnotacredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notascreditodetalle> notascreditodetalle { get; set; }
    }
}
