//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagos
    {
        public long pago_id { get; set; }
        public Nullable<long> pago_transaccion_id { get; set; }
        public Nullable<long> pago_cuota_id { get; set; }
        public Nullable<decimal> pago_cuota_monto { get; set; }
        public Nullable<System.DateTime> pago_fechacreacion { get; set; }
        public Nullable<long> pago_usuariocreacion { get; set; }
        public Nullable<System.DateTime> pago_fechamodificacion { get; set; }
        public Nullable<long> pago_usuariomodificacion { get; set; }
        public string pago_descripcion { get; set; }
        public Nullable<decimal> pago_montodescuento { get; set; }
        public Nullable<decimal> pago_montonetopago { get; set; }
        public Nullable<bool> pago_estado { get; set; }
    
        public virtual cuotas cuotas { get; set; }
        public virtual transacciones transacciones { get; set; }
    }
}
