//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proformascontrato
    {
        public long proformacontrato_id { get; set; }
        public Nullable<long> proformacontrato_contrato_id { get; set; }
        public Nullable<long> proformacontrato_proformauif_id { get; set; }
        public Nullable<long> proformacontrato_tipopropetario_id { get; set; }
        public Nullable<System.DateTime> proformacontrato_fechacreacion { get; set; }
        public Nullable<long> proformacontrato_usuariocreacion { get; set; }
        public Nullable<System.DateTime> proformacontrato_fechamodificacion { get; set; }
        public Nullable<long> proformacontrato_usuariomodificacion { get; set; }
    }
}
