//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class provincias
    {
        public long provincia_id { get; set; }
        public Nullable<long> provincia_departamento_id { get; set; }
        public string provincia_codigo { get; set; }
        public string provincia_descripcion { get; set; }
    
        public virtual departamentos departamentos { get; set; }
    }
}
