//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class series
    {
        public long serie_id { get; set; }
        public Nullable<long> serie_empresa_id { get; set; }
        public Nullable<long> serie_tipodocumentoventa_id { get; set; }
        public string serie_serie { get; set; }
        public Nullable<long> serie_numeracion { get; set; }
    
        public virtual empresas empresas { get; set; }
        public virtual tiposdocumentoventa tiposdocumentoventa { get; set; }
    }
}
