//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiposmoneda
    {
        public long tipomoneda_id { get; set; }
        public string tipomoneda_idanterior { get; set; }
        public string tipomoneda_descripcioncorta { get; set; }
        public string tipomoneda_descripcion { get; set; }
    }
}
