//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class titulares
    {
        public long titular_id { get; set; }
        public Nullable<long> titular_empresa_id { get; set; }
        public string titular_nombre { get; set; }
        public string titular_nrodocumento { get; set; }
    
        public virtual empresas empresas { get; set; }
    }
}
