//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaccionesseparacion
    {
        public long transaccionseparacion_id { get; set; }
        public Nullable<long> transaccionseparacion_separacion_id { get; set; }
        public Nullable<long> transaccionseparacion_transaccion_id { get; set; }
        public Nullable<System.DateTime> transaccionseparacion_fechacreacion { get; set; }
        public Nullable<long> transaccionseparacion_usuariocreacion { get; set; }
        public Nullable<System.DateTime> transaccionseparacion_fechamodificacion { get; set; }
        public Nullable<long> transaccionseparacion_usuariomodificacion { get; set; }
        public string transaccionseparacion_descripcion { get; set; }
    
        public virtual separaciones separaciones { get; set; }
        public virtual transacciones transacciones { get; set; }
    }
}
