//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_cargarEventos
    {
        public string start { get; set; }
        public Nullable<long> evento_estadoevento_id { get; set; }
        public string title { get; set; }
        public long evento_id { get; set; }
    }
}
