//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_reporteVentas
    {
        public long documentoventa_id { get; set; }
        public string documentoEmision { get; set; }
        public string notacreditoanulacion { get; set; }
        public string documentoventa_cliente_nrodocumento { get; set; }
        public string documentoventa_cliente_nombre { get; set; }
        public Nullable<decimal> documentoventa_total { get; set; }
        public string documentoventa_moneda_codigo { get; set; }
        public string documentoventa_fechaemision { get; set; }
        public Nullable<System.DateTime> documentoventa_fechacreacion { get; set; }
        public Nullable<long> documentoventa_transaccion_id { get; set; }
        public Nullable<long> cotizacion_proyecto_id { get; set; }
        public Nullable<long> anexocontratocotizacion_contrato_id { get; set; }
        public string notacredito_fechaemision { get; set; }
    }
}
