//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_vivemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_reporteeventos
    {
        public Nullable<long> evento_contrato_id { get; set; }
        public long evento_id { get; set; }
        public string proformauif_cliente_nrodocumento { get; set; }
        public string proformauif_cliente_razonsocial { get; set; }
        public string proyecto_nombrecorto { get; set; }
        public Nullable<long> proyecto_id { get; set; }
        public string cotizacion_lote_nombre { get; set; }
        public Nullable<int> llamada { get; set; }
        public Nullable<int> whatsapp { get; set; }
        public Nullable<int> correo { get; set; }
        public Nullable<int> entrevista { get; set; }
    }
}
